apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-deployment
spec:
  selector:
    matchLabels:
      app: identity
  template:
    metadata:
      labels:
        app: identity
    spec:
      serviceAccountName: identity-serviceaccount
      containers:
      - name: identity
        image: wbplayeconomy.azurecr.io/play.identity:1.0.7
        imagePullPolicy: Always
        env:
          - name: ServiceSettings__MessageBroker
            value: SERVICEBUS
          - name: ServiceSettings__KeyVaultName
            value: wbplayeconomy
        resources:
          limits:
            memory: "128Mi"
            cpu: "150m"
        ports:
        - containerPort: 5002
        livenessProbe:
          httpGet:
            path: /health/live
            port: 5002
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 5002
          initialDelaySeconds: 10          

---
apiVersion: v1
kind: Service
metadata:
  name: identity-service
spec:
  type: LoadBalancer
  selector:
    app: identity
  ports:
  - port: 80
    targetPort: 5002

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: identity-serviceaccount
  annotations:
    azure.workload.identity/client-id: 3a9b8ac0-6c1f-4b91-b320-254c3e761c1c
  labels:
    azure.workload.identity/use: "true"