apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-deployment
spec:
  selector:
    matchLabels:
      app: identity
  template:
    metadata:
      labels:
        app: identity
    spec:
      containers:
      - name: identity
        image: wbplayeconomy.azurecr.io/play.identity:1.0.5
        env:
          - name: ServiceSettings__MessageBroker
            value: SERVICEBUS
          - name: MongoDbSettings__ConnectionString
            valueFrom:
              secretKeyRef:
                name: identity-secrets
                key: cosmodb-connectionstring
          - name: ServiceBusSettings__ConnectionString
            valueFrom:
              secretKeyRef:
                name: identity-secrets
                key: servicebus-connectionstring
          - name: IdentitySettings__AdminUserPassword
            valueFrom:
              secretKeyRef:
                name: identity-secrets
                key: admin-password
        resources:
          limits:
            memory: "128Mi"
            cpu: "150m"
        ports:
        - containerPort: 5002
        livenessProbe:
          httpGet:
            path: /health/live
            port: 5002
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 5002
          initialDelaySeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: identity-service
spec:
  type: LoadBalancer
  selector:
    app: identity
  ports:
  - port: 80
    targetPort: 5002

