microserviceName: "identity"

image:
  repository: wbplayeconomy.azurecr.io/play.identity
  tag: 1.0.11

envVariables:
  IdentitySettings__PathBase: /identity-svc
  IdentitySettings__CertificateCerFilePath: "/certificates/certificate.crt"
  IdentitySettings__CertificateKeyFilePath: "/certificates/certificate.key"  
  IdentityServerSettings__Clients__0__RedirectUris__0: https://wbplayeconomy.eastus.cloudapp.azure.com/authentication/login-callback
  IdentityServerSettings__Clients__0__PostLogoutRedirectUris__0: https://wbplayeconomy.eastus.cloudapp.azure.com/authentication/logout-callback

container:
  port: 5002
  volumeMounts:
    - name: certificate-volume
      mountPath: /certificates    

volumes:
  - name: certificate-volume
    secret:
      secretName: signing-cert
      items:
        - key: tls.key
          path: certificate.key
        - key: tls.crt
          path: certificate.crt

certificate:
  secretName: signing-cert
  hostname: wbplayeconomy.eastus.cloudapp.azure.com

identityClientId: 3a9b8ac0-6c1f-4b91-b320-254c3e761c1c